name: Dependency review
on:
  pull_request:
  merge_group:
    types: [checks_requested]
permissions: {}
concurrency:
  group: dependency-review-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  review:
    name: Dependency review
    permissions:
      contents: read
    uses: nix-forge/ci/.github/workflows/dependency-review.yml@bb1b39a9082f72dc6c7ce596103ce7a5e4d29b01 # v2.8.0
