name: Dependency review
on:
  pull_request:
  merge_group:
    types: [checks_requested]
permissions: {}
concurrency:
  group: dependency-review-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  review:
    name: Dependency review
    permissions:
      contents: read
    uses: nix-forge/ci/.github/workflows/dependency-review.yml@d84cb92725a2ab7eafcdc9d1f1fb7a06048dfa1a # v2.2.0
