name: Dependency review
on:
  pull_request:
permissions: {}
concurrency:
  group: dependency-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  review:
    name: Dependency review
    permissions:
      contents: read
    uses: nix-forge/ci/.github/workflows/dependency-review.yml@679f99ac3b2c8e25d2b2049c1b21541c51dc71ee # v1.0.2
